<?php
/*plugin Name: Advance Login Register
plugin URI:   https://www.goiALR.com
Description:  Simple WordPress plugin for LoALRn ReALRster
Version:      1.0.0
Author:       IALR
Author URI:   https://www.goiALR.com
License:      GPL2
License URI:  https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:  wporg
Domain Path:  /languages
License:     GPL2
 
{Advance LoALRn ReALRster} is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
any later version.
 
{Advance LoALRn ReALRster} is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
 
You should have received a copy of the GNU General Public License
along with {plugin Name}. If not, see {License URI}.
*/
/*
 * Option Page Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
*/
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit; 
}
// Define WC_plugin_FILE.
if ( ! defined( 'ALR_FILE' ) ) {
	define( 'ALR_FILE', __FILE__ );
}
define("ALR_URL", plugin_dir_url( __FILE__ ));//=> http://localhost/testing/wp-content/plugins/advance-login-register/ 
define("ALR_ROOT_URI", plugins_url( __FILE__ ));//=>http://localhost/testing/wp-content/plugins/C:/xampp/htdocs/testing/wp-content/plugins/advance-login-register/alr.php 
define("ADMIN_URI", admin_url()); //=>http://localhost/testing/wp-admin/ 
define("PATH", __DIR__); //=>C:\xampp\htdocs\testing\wp-content\plugins\advance-login-register 
define('DIR_PATH', plugin_dir_path( __FILE__ ));//=> C:\xampp\htdocs\testing\wp-content\plugins\advance-login-register/

class ALR{
	public function __construct(){
		add_shortcode('alr', array($this,'alr_callback'));
		add_action('wp_enqueue_scripts', array( $this, 'alr_enqueue_script' ) );
		add_action('after_setup_theme', array( $this,'create_page_template'));
		add_filter( 'template_include', 'wp_page_template' );

	}


    function wp_page_template( $page_template )
    {
        if ( is_page( 'Login' ) ) {
            $page_template = DIR_PATH . 'templates/login.php';
        }
        return $page_template;
    }


	public function create_page_template(){

		$temp =  DIR_PATH . '/templates/login.php';
		//echo $temp;

		$page_id = get_option('login_page_id2');
		if(!$page_id){
			$args = array(
			'post_title' => "Login2",
			'post_content' => "[alr]",
			'post_status' => "publish",
			'post_type' => 'page',
			'page_template' => $temp
		);
			$post_id = wp_insert_post($args, $error);
			update_option("login_page_id2",$post_id);
		}
	}
	public function alr_callback(){
		
		
		require_once('inc/login-form.php');
	}
	//enque script 
	public function alr_enqueue_script() {   
	wp_enqueue_style ('bootstrap',  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'  );
	wp_enqueue_style ('style1', 'http://fonts.googleapis.com/css?family=Open+Sans'  );
	wp_enqueue_style ('style2', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'  );
	wp_enqueue_style ('style', ALR_URL. 'css/style.css'  );
	
	wp_enqueue_script( 'jquery', ALR_URL . 'js/jquery.min.js', array(), false, true );
	wp_enqueue_script('bootstrapjs', '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js', array(), null, true);
    wp_enqueue_script( 'my_custom_script', ALR_URL . 'js/script.js', array(), false, true);
    wp_enqueue_script( 'CustomformValidation', ALR_URL . 'js/CustomformValidation.js', array(), false, true);
    wp_enqueue_script( 'login-validate', ALR_URL . 'js/login-validate.js', array(), false, true);
	}
}
new ALR();

